application: cutting-masala-chai
version: testing
runtime: python
api_version: 1

default_expiration: 7d

handlers:
- url: .*/favicon\.ico
  static_files: public/image/logo/favicon.png
  upload: public/image/logo/favicon.png
  secure: never

- url: /xd_receiver.html
  static_files: public/html/facebook/xd_receiver.html
  upload: public/html/facebook/xd_receiver.html
  secure: never

- url: /robots\.txt
  static_files: public/robots.txt
  upload: public/robots.txt
  secure: never

- url: /s
  static_dir: public
  secure: never
  expiration: 7d

- url: /console/static
  static_dir: console/app/view/static
  secure: never

#- url: /facebook/invite/xd_receiver.html
#  static_files: public/html/xd_receiver.html
#  upload: public/html/xd_receiver.html

- url: /console.*
  script: console/app/console.py

- url: .*
  script: handlers.py

skip_files: |
  ^(.*/)?(
  (app\.yaml)|
  (app\.yml)|
  (index\.yaml)|
  (index\.yml)|
  (#.*#)|
  (.*~)|
  (.*\.py[co])|
  (.*\.bak)|
  (.*\.gitignore)|
  (\..*)
  )$
