application: cutting-masala-chai
version: development
runtime: python
api_version: 1

default_expiration: 30d

handlers:
- url: .*/favicon\.ico
  static_files: public/image/logo/favicon.png
  upload: public/image/logo/favicon.png
  secure: never

- url: /xd_receiver.html
  static_files: public/html/facebook/xd_receiver.html
  upload: public/html/facebook/xd_receiver.html
  secure: never

- url: /robots\.txt
  static_files: public/robots.txt
  upload: public/robots.txt
  secure: never

- url: /s
  static_dir: public
  secure: never

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/deferred.py
  login: admin

- url: /console/static
  static_dir: console/app/view/static
  secure: never

- url: /facebox
  static_dir: public/image/facebox
  secure: never
  
- url: /appengine_admin_media/
  static_dir: appengine_admin/media
  secure: never

#- url: /facebook/invite/xd_receiver.html
#  static_files: public/html/xd_receiver.html
#  upload: public/html/xd_receiver.html

- url: /console.*
  script: console/app/console.py
  login: admin

- url: /admin.*
  script: admin.py
  login: admin

- url: /_oid.*
  script: oid.py

- url: /dl.*
  script: static.py

- url: .*
  script: handlers.py

skip_files: |
  ^(.*/)?(
  (app\.yaml)|
  (app\.yml)|
  (index\.yaml)|
  (index\.yml)|
  (#.*#)|
  (.*~)|
  (.*\.py[co])|
  (.*\.bak)|
  (.*\.gitignore)|
  (\..*)
  )$
