application: cutting-masala-chai
version: sandbox
runtime: python
api_version: 1

default_expiration: 7d

handlers:
- url: /favicon.ico
  static_files: public/image/icon/favicon.png
  upload: public/image/icon/favicon.png
  secure: never

- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt
  secure: never

#- url: /facebook/invite/xd_receiver.html
#  static_files: public/html/xd_receiver.html
#  upload: public/html/xd_receiver.html

- url: /s
  static_dir: public
  secure: never
  expiration: 7d

- url: /.*
  script: handlers.py
